services:
  docker-dev:
    build: .
    container_name: docker-dev
    volumes:
      - ~/repo:/workspace
      - ~/.nvm:/home/user/.nvm
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5173:5173"
      - "5174:5174"
      - "8080:8080"
      - "8081:8081"
    network_mode: bridge
    stdin_open: true
    tty: true
