name: docker
services:
  dev:
    build:
      context: .
      args:
        USERNAME: ${USER}
    container_name: dev
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

      - ~/.docker-dev:/home/${USER}/.docker-dev
      - ~/.nvm:/home/${USER}/.nvm

      # Replace `dev` by the name of your main workspace folder
      - ~/dev:/home/${USER}/dev

      # If you use the file `~/.config/git/ignore`, activate this line:
      #- ~/.config/git/ignore:/home/${USER}/.config/git/ignore

    network_mode: bridge
    stdin_open: true
    tty: true
